# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-03-11 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seria_numb', models.CharField(max_length=255, verbose_name='Seria number')),
                ('card_number', models.CharField(max_length=255, verbose_name='Card number')),
                ('release_date', models.DateField(verbose_name='Card release date')),
                ('activity_end_date', models.DateField(verbose_name='Card activity end date')),
                ('use_date', models.DateTimeField(blank=True, null=True, verbose_name='Card use date')),
                ('amount', models.FloatField(default=0.0, verbose_name='Card amount')),
                ('status', models.CharField(choices=[('not_activated', 'Not activated'), ('activated', 'Activated'), ('expired', 'Expired')], default='not_activated', max_length=125, verbose_name='Card status')),
            ],
        ),
    ]
