# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-03-11 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseHistoryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_one_title', models.CharField(max_length=255, verbose_name='Purchase one title')),
                ('purchase_amount', models.FloatField(default=0.0, verbose_name='Purchase amount')),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name='Purchase date')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardApp.Card', verbose_name='Purchase History Card')),
            ],
        ),
    ]
